CREATE DATABASE countries_sundries;

USE countries_sundries;

CREATE TABLE Region(
    id_region INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE Sub_Region(
    id_sub_region INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    id_region INT NOT NULL,
    FOREIGN KEY(id_region) REFERENCES Region(id_region)
);

CREATE TABLE Date_Format(
    id_date_format INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    format VARCHAR(30) NOT NULL
);

CREATE TABLE Currency(
    id_currency INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    abbr VARCHAR(20) NOT NULL,
    name VARCHAR(40) NOT NULL,
    symbol VARCHAR(30) NOT NULL
);

CREATE TABLE Flag(
    id_flag INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL,
    url VARCHAR(255) NOT NULL
);

CREATE TABLE Coat_Of_Arm(
    id_coat_of_arm INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL,
    url VARCHAR(255) NOT NULL
);

CREATE TABLE Country(
    id_country INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    official_name VARCHAR(100) NOT NULL,
    abbr VARCHAR(5) NOT NULL,
    internet_tld VARCHAR(20) NOT NULL,
    motto VARCHAR(100),
    anthem VARCHAR(100),
    capital VARCHAR(100) NOT NULL,
    official_language VARCHAR(50) NOT NULL,
    population INT NOT NULL,
    iso_3166_1_alpha_2 VARCHAR(5) NOT NULL,
    iso_3166_1_alpha_3 VARCHAR(5) NOT NULL,
    calling_code VARCHAR(7) NOT NULL,
    timezone VARCHAR(20) NOT NULL,
    id_coat_of_arm INT NULL,
    id_flag INT NULL,
    id_currency INT NULL,
    id_date_format INT NULL,
    id_region INT NULL,
    id_sub_region INT NULL,
    FOREIGN KEY(id_coat_of_arm) REFERENCES Coat_Of_Arm(id_coat_of_arm),
    FOREIGN KEY(id_flag) REFERENCES Flag(id_flag),
    FOREIGN KEY(id_currency) REFERENCES Currency(id_currency),
    FOREIGN KEY(id_date_format) REFERENCES Date_Format(id_date_format),
    FOREIGN KEY(id_region) REFERENCES Region(id_region),
    FOREIGN KEY(id_sub_region) REFERENCES Sub_Region(id_sub_region)
);



/* Region inserts */
INSERT INTO Region(name)
VALUES
    ('America'),
    ('Asia'),
    ('Africa'),
    ('Europe'),
    ('Oceania'),
    ('Antartica');



/* Sub_Region inserts */
INSERT INTO Sub_Region(name, id_region)
VALUES
    ('South America', 1),
    ('Caribbean', 1),
    ('Central America', 1),
    ('Northern America', 1);

INSERT INTO Sub_Region(name, id_region)
VALUES
    ('Central Asia', 2),
    ('Eastern Asia', 2),
    ('South-eastern Asia', 2),
    ('Sourthern Asia', 2),
    ('Western Asia', 2),
    ('Middle East', 2);

INSERT INTO Sub_Region(name, id_region)
VALUES
    ('Northern Africa', 3),
    ('Eastern Africa', 3),
    ('Middle Africa', 3),
    ('Southern Africa', 3),
    ('Western Africa', 3);

INSERT INTO Sub_Region(name, id_region)
VALUES
    ('Eastern Europe', 4),
    ('Northern Europe', 4),
    ('Southern Europe', 4),
    ('Western Europe', 4);

INSERT INTO Sub_Region(name, id_region)
VALUES
    ('Australia and New Zealand', 5),
    ('Melanesia', 5),
    ('Micronesia', 5),
    ('Polynesia', 5);

INSERT INTO Sub_Region(name, id_region)
VALUES
    ('North-east Antarctic Peninsula', 6),
    ('South Orkney Islands', 6),
    ('North-west Antarctic Peninsula', 6),
    ('Enderby Land', 6),
    ('Dronning Maud Land', 6),
    ('East Antarctica', 6),
    ('North Victoria Land', 6),
    ('South Victoria Land', 6),
    ('Transantarctic Mountains', 6),
    ('Ellsworth Mountains', 6),
    ('Marie Byrd Land', 6),
    ('Adélie Land', 6),
    ('Ellsworth Land', 6),
    ('South Antarctic Peninsula.', 6);



/* Date_Format inserts */
INSERT INTO Date_Format(format)
VALUES
    ('dd/mm/yyyy'),
    ('yyyy/mm/dd'),
    ('mm/dd/yyyy');



/* Currency inserts */
INSERT INTO Currency(abbr, name, symbol)
VALUES
    ('ARS', 'Argentine Peso', '$'),
    ('AED', 'Emirati Dirham', 'د.إ'),
    ('AFN', 'Afghan Afghani', '؋'),
    ('ALL', 'Albanian Lek', 'Lek'),
    ('DZD', 'Algerian Dinar', 'DA'),
    ('USD', 'US Dollar', '$'),
    ('AOA', 'Angolan Kwanza', 'Kz'),
    ('AMD', 'Armenian Dram', '֏'),
    ('AUD', 'Australian Dollar', '$'),
    ('AZN', 'Azerbaijan Manat', '₼'),
    ('BHD', 'Bahraini Dinar', 'BD'),
    ('BDT', 'Bangladeshi Taka', 'Tk'),
    ('BBD', 'Barbados Dollar', '$'),
    ('BYN', 'Belarusian Ruble', 'p.'),
    ('BZD', 'Belizean Dollar', 'BZ$'),
    ('BTN', 'Bhutanese Ngultrum', 'Ngultrum'),
    ('BOB', 'Bolivian Bolíviano', '$b'),
    ('BAM', 'Bosnian Convertible Mark', 'KM'),
    ('BWP', 'Botswana Pula', 'P'),
    ('BRL', 'Brazilian Real', 'R$'),
    ('GBP', 'British Pound', '£'),
    ('BND', 'Bruneian Dollar', '$'),
    ('BGN', 'Bulgarian Lev', 'лв'),
    ('BIF', 'Burundian Franc', 'Franc'),
    ('KHR', 'Cambodian Riel', '៛'),
    ('CAD', 'Canadian Dollar', '$'),
    ('XAF', 'Central African CFA Franc BEAC', 'XAF'),
    ('CLP', 'Chilean Peso', '$'),
    ('CNY', 'Chinese Yuan Renminbi', '¥'),
    ('COP', 'Colombian Peso', '$'),
    ('KMF', 'Comorian Franc', 'Franc'),
    ('CRC', 'Costa Rican Colon', '₡'),
    ('HRK', 'Croatian Kuna', 'kn'),
    ('CUP', 'Cuban Peso', '₱'),
    ('CZK', 'Czech Koruna', 'Kč'),
    ('DKK', 'Danish Krone', 'kr.'),
    ('CDF', 'Congolese Franc', 'Franc'),
    ('DJF', 'Djiboutian Franc', 'Franc'),
    ('DOP', 'Dominican Peso', 'RD$'),
    ('EUR', 'Euro', '€'),
    ('EGP', 'Egyptian Pound', '£'),
    ('ERN', 'Eritrean Nakfa', 'Nkf'),
    ('ETB', 'Ethiopian Birr', 'Br'),
    ('FJD', 'Fijian Dollar', '$'),
    ('PHP', 'Philippine Peso', '₱'),
    ('AWG', 'Aruban or Dutch Guilder', 'ƒ'),
    ('BMD', 'Bermudian Dollar', '$'),
    ('CVE', 'Cape Verdean Escudo', '$'),
    ('XOF', 'CFA Franc', 'Franc'),
    ('SZL', 'Swazi Lilangeni', 'Lilangeni'),
    ('XPF', 'CFP Franc', 'Franc'),
    ('GGP', 'Guernsey Pound', '£'),
    ('JEP', 'Jersey Pound', 'p'),
    ('LSL', 'Basotho Loti', 'Loti'),
    ('MOP', 'Macau Pataca', 'MOP$'),
    ('MDL', 'Moldovan Leu', 'lei'),
    ('MMK', 'Burmese Kyat', 'K'),
    ('NIO', 'Nicaraguan Cordoba', 'C$'),
    ('MKD', 'Macedonian Denar', 'ден'),
    ('SHP', 'Saint Helenian Pound', '£'),
    ('SLE', 'Sierra Leonean Leone', 'Le'),
    ('ZAR', 'South African Rand', 'R'),
    ('BSD', 'Bahamian Dollar', '$'),
    ('KYD', 'Caymanian Dollar', '$'),
    ('FKP', 'Falkland Island Pound', '£'),
    ('FOK', 'Faroese Króna', 'kr'),
    ('GMD', 'Gambian Dalasi', 'Dalasi'),
    ('GIP', 'Gibraltar Pound', '£'),
    ('IMP', 'Isle of Man Pound', '£'),
    ('ANG', 'Dutch Guilder', 'ƒ'),
    ('HKD', 'Hong Kong Dollar', 'HK$'),
    ('TRY', 'Turkish Lira', '₺'),
    ('GEL', 'Georgian Lari', 'Lari'),
    ('GHS', 'Ghanaian Cedi', 'GH¢'),
    ('GTQ', 'Guatemalan Quetzal', 'Q'),
    ('GNF', 'Guinean Franc', 'Franc'),
    ('GYD', 'Guyanese Dollar', '$'),
    ('HTG', 'Haitian Gourde', 'G'),
    ('HNL', 'Honduran Lempira', 'L'),
    ('HUF', 'Hungarian Forint', 'Ft'),
    ('ISK', 'Icelandic Krona', 'kr'),
    ('XDR', 'IMF Special Drawing Rights', 'Special Drawing Rights'),
    ('INR', 'Indian Rupee', '₹'),
    ('IDR', 'Indonesian Rupiah', 'Rp'),
    ('IRR', 'Iranian Rial', '﷼'),
    ('IQD', 'Iraqi Dinar', 'د.ع'),
    ('ILS', 'Israeli Shekel', '₪'),
    ('JMD', 'Jamaican Dollar', 'J$'),
    ('JPY', 'Japanese Yen', '¥'),
    ('JOD', 'Jordanian Dinar', 'Dinar'),
    ('KZT', 'Kazakhstani Tenge', '₸'),
    ('KES', 'Kenyan Shilling', 'KSh'),
    ('KID', 'Kiribati Dollar', '$'),
    ('KWD', 'Kuwaiti Dinar', 'ك'),
    ('KGS', 'Kyrgyzstani Som', 'лв'),
    ('LAK', 'Lao Kip', '₭'),
    ('LBP', 'Lebanese Pound', 'ل.ل'),
    ('LRD', 'Liberian Dollar', '$'),
    ('LYD', 'Libyan Dinar', 'LD'),
    ('MGA', 'Malagasy Ariary', 'Ar'),
    ('MWK', 'Malawian Kwacha', 'MK'),
    ('MYR', 'Malaysian Ringgit', 'RM'),
    ('MVR', 'Maldivian Rufiyaa', 'Rufiyaa'),
    ('MRU', 'Mauritanian Ouguiya', 'UM'),
    ('MUR', 'Mauritanian Rupee', 'Rs'),
    ('MXN', 'Mexican Peso', '$'),
    ('MNT', 'Mongolian Tughrik', '₮'),
    ('MAD', 'Moroccan Dirham', 'Dirham'),
    ('MZN', 'Mozambican Metical', 'MT'),
    ('NAD', 'Namibian Dollar', '$'),
    ('NPR', 'Nepalese Rupee', '₨'),
    ('NZD', 'New Zealand Dollar', '$'),
    ('NGN', 'Nigerian Naira', '₦'),
    ('NOK', 'Norwegian Krone', 'kr'),
    ('XCD', 'East Caribbean Dollar', '$'),
    ('OMR', 'Omani Rial', '﷼'),
    ('PKR', 'Pakistani Rupee', '₨'),
    ('PAB', 'Panamanian Balboa', 'B/.'),
    ('PGK', 'Papua New Guinean Kina', 'K'),
    ('PYG', 'Paraguayan Guarani', 'Gs'),
    ('PEN', 'Peruvian Sol', 'S/.'),
    ('PLN', 'Polish Zloty', 'zł'),
    ('QAR', 'Qatari Riyal', '﷼'),
    ('RON', 'Romanian Leu', 'lei'),
    ('RUB', 'Russian Ruble', '₽'),
    ('RWF', 'Rwandan Franc', 'Franc'),
    ('WST', 'Samoan Tala', '$'),
    ('STN', 'Sao Tomean Dobra', 'Db'),
    ('SAR', 'Saudi Arabian Riyal', '﷼'),
    ('RSD', 'Serbian Dinar', 'РСД'),
    ('SCR', 'Seychellois Rupee', '₨'),
    ('SGD', 'Singapore Dollar', '$'),
    ('SBD', 'Solomon Islander Dollar', '$'),
    ('SOS', 'Somali Shilling', 'S'),
    ('KRW', 'South Korean Won', '₩'),
    ('SSP', 'South Sudanese Pound', 'Pound'),
    ('LKR', 'Sri Lankan Rupee', '₨'),
    ('SDG', 'Sudanese Pound', 'Pound'),
    ('SRD', 'Surinamese Dollar', '$'),
    ('SEK', 'Swedish Krona', 'kr'),
    ('CHF', 'Swiss Franc', 'CHF'),
    ('SYP', 'Syrian Pound', '£'),
    ('TWD', 'Taiwan New Dollar', 'NT$'),
    ('TJS', 'Tajikistani Somoni', 'Somoni'),
    ('TZS', 'Tanzanian Shilling', 'Shilling'),
    ('THB', 'Thai Baht', '฿'),
    ('TOP', "Tongan Pa'anga", 'T$'),
    ('TTD', 'Trinidadian Dollar', 'TT$'),
    ('TND', 'Tunisian Dinar', 'Dinar'),
    ('TMT', 'Turkmenistani Manat', 'Manat'),
    ('TVD', 'Tuvaluan Dollar', '$'),
    ('UGX', 'Ugandan Shilling', 'UGX'),
    ('UAH', 'Ukrainian Hryvnia', '₴'),
    ('UYU', 'Uruguayan Peso', '$U'),
    ('UZS', 'Uzbekistani Som', 'лв'),
    ('VUV', 'Ni-Vanuatu Vatu', 'VT'),
    ('VES', 'Venezuelan Bolívar', 'Bs.'),
    ('VND', 'Vietnamese Dong', '₫'),
    ('YER', 'Yemeni Rial', '﷼'),
    ('ZMW', 'Zambian Kwacha', 'ZK'),
    ('ZWL', 'Zimbabwean Dollar', 'Z$');

/* Flag inserts */
INSERT INTO Flag(name, type, url)
VALUES
    ('argentina', 'svg', 'argentina.svg'),
    ('afghanistan', 'svg', 'afghanistan.svg'),
    ('albania', 'svg', 'albania.svg'),
    ('algeria', 'svg', 'algeria.svg'),
    ('angola', 'svg', 'angola.svg'),
    ('armenia', 'svg', 'armenia.svg'),
    ('aruba', 'svg', 'aruba.svg'),
    ('australia', 'svg', 'australia.svg'),
    ('azerbaijan', 'svg', 'azerbaijan.svg'),
    ('bahrain', 'svg', 'bahrain.svg'),
    ('bangladesh', 'svg', 'bangladesh.svg'),
    ('barbados', 'svg', 'barbados.svg'),
    ('belarus', 'svg', 'belarus.svg'),
    ('belize', 'svg', 'belize.svg'),
    ('benin', 'svg', 'benin.svg'),
    ('bermuda', 'svg', 'bermuda.svg'),
    ('bhutan', 'svg', 'bhutan.svg'),
    ('bolivia', 'svg', 'bolivia.svg'),
    ('bosnia_and_herzegovina', 'svg', 'bosnia_and_herzegovina.svg'),
    ('botswana', 'svg', 'botswana.svg'),
    ('brazil', 'svg', 'brazil.svg'),
    ('brunei', 'svg', 'brunei.svg'),
    ('bulgaria', 'svg', 'bulgaria.svg'),
    ('burundi', 'svg', 'burundi.svg'),
    ('cambodia', 'svg', 'cambodia.svg'),
    ('canada', 'svg', 'canada.svg'),
    ('cape_verde', 'svg', 'cape_verde.svg'),
    ('chile', 'svg', 'chile.svg'),
    ('coat_of_arms', 'svg', 'coat_of_arms.svg'),
    ('colombia', 'svg', 'colombia.svg'),
    ('comoros', 'svg', 'comoros.svg'),
    ('costa_rica', 'svg', 'costa_rica.svg'),
    ('croatia', 'svg', 'croatia.svg'),
    ('cuba', 'svg', 'cuba.svg'),
    ('denmark', 'svg', 'denmark.svg'),
    ('djibouti', 'svg', 'djibouti.svg'),
    ('egypt', 'svg', 'egypt.svg'),
    ('el_salvador', 'svg', 'el_salvador.svg'),
    ('england', 'svg', 'england.svg'),
    ('eritrea', 'svg', 'eritrea.svg'),
    ('eswatini', 'svg', 'eswatini.svg'),
    ('ethiopia', 'svg', 'ethiopia.svg'),
    ('europe', 'svg', 'europe.svg'),
    ('fiji', 'svg', 'fiji.svg'),
    ('french_polynesia', 'svg', 'french_polynesia.svg'),
    ('georgia', 'svg', 'georgia.svg'),
    ('ghana', 'svg', 'ghana.svg'),
    ('gibraltar', 'svg', 'gibraltar.svg'),
    ('grenada', 'svg', 'grenada.svg'),
    ('guatemala', 'svg', 'guatemala.svg'),
    ('guernsey', 'svg', 'guernsey.svg'),
    ('guinea', 'svg', 'guinea.svg'),
    ('guyana', 'svg', 'guyana.svg'),
    ('haiti', 'svg', 'haiti.svg'),
    ('honduras', 'svg', 'honduras.svg'),
    ('hong_kong', 'svg', 'hong_kong.svg'),
    ('hungary', 'svg', 'hungary.svg'),
    ('iceland', 'svg', 'iceland.svg'),
    ('india', 'svg', 'india.svg'),
    ('indonesia_garuda_pancasila', 'svg', 'indonesia_garuda_pancasila.svg'),
    ('international_monetary_fund_logo', 'svg', 'international_monetary_fund_logo.svg'),
    ('iran', 'svg', 'iran.svg'),
    ('iraq', 'svg', 'iraq.svg'),
    ('israel_alternative', 'svg', 'israel_alternative.svg'),
    ('jamaica', 'svg', 'jamaica.svg'),
    ('japan', 'svg', 'japan.svg'),
    ('jersey', 'svg', 'jersey.svg'),
    ('jordan', 'svg', 'jordan.svg'),
    ('kazakhstan', 'svg', 'kazakhstan.svg'),
    ('kenya', 'svg', 'kenya.svg'),
    ('kiribati', 'svg', 'kiribati.svg'),
    ('kuwait', 'svg', 'kuwait.svg'),
    ('kyrgyzstan', 'svg', 'kyrgyzstan.svg'),
    ('laos', 'svg', 'laos.svg'),
    ('lebanon', 'svg', 'lebanon.svg'),
    ('lesotho', 'svg', 'lesotho.svg'),
    ('liberia', 'svg', 'liberia.svg'),
    ('libya', 'svg', 'libya.svg'),
    ('macau', 'svg', 'macau.svg'),
    ('madagascar', 'svg', 'madagascar.svg'),
    ('malawi', 'svg', 'malawi.svg'),
    ('malaysia', 'svg', 'malaysia.svg'),
    ('maldives', 'svg', 'maldives.svg'),
    ('mauritania', 'svg', 'mauritania.svg'),
    ('mauritius', 'svg', 'mauritius.svg'),
    ('mexico', 'svg', 'mexico.svg'),
    ('moldova', 'svg', 'moldova.svg'),
    ('mongolia', 'svg', 'mongolia.svg'),
    ('morocco', 'svg', 'morocco.svg'),
    ('mozambique', 'svg', 'mozambique.svg'),
    ('myanmar', 'svg', 'myanmar.svg'),
    ('namibia', 'svg', 'namibia.svg'),
    ('nepal', 'svg', 'nepal.svg'),
    ('new_zealand', 'svg', 'new_zealand.svg'),
    ('nicaragua', 'svg', 'nicaragua.svg'),
    ('nigeria', 'svg', 'nigeria.svg'),
    ('north_macedonia', 'svg', 'north_macedonia.svg'),
    ('norway', 'svg', 'norway.svg'),
    ('oman', 'svg', 'oman.svg'),
    ('papua_new_guinea', 'svg', 'papua_new_guinea.svg'),
    ('pakistan', 'svg', 'pakistan.svg'),
    ('panama', 'svg', 'panama.svg'),
    ('paraguay', 'svg', 'paraguay.svg'),
    ('per', 'svg', 'per.svg'),
    ('polski', 'svg', 'polski.svg'),
    ('qatar', 'svg', 'qatar.svg'),
    ('romania', 'svg', 'romania.svg'),
    ('rwanda', 'svg', 'rwanda.svg'),
    ('saint_helena', 'svg', 'saint_helena.svg'),
    ('samoa', 'svg', 'samoa.svg'),
    ('saudi_arabia', 'svg', 'saudi_arabia.svg'),
    ('serbia', 'svg', 'serbia.svg'),
    ('seychelles', 'svg', 'seychelles.svg'),
    ('sierra_leone', 'svg', 'sierra_leone.svg'),
    ('singapore', 'svg', 'singapore.svg'),
    ('somalia', 'svg', 'somalia.svg'),
    ('south_africa_heraldic', 'svg', 'south_africa_heraldic.svg'),
    ('south_korea', 'svg', 'south_korea.svg'),
    ('south_sudan', 'svg', 'south_sudan.svg'),
    ('sao_tome_and_prncipe', 'svg', 'sao_tome_and_prncipe.svg'),
    ('sri_lanka', 'svg', 'sri_lanka.svg'),
    ('sudan', 'svg', 'sudan.svg'),
    ('suriname', 'svg', 'suriname.svg'),
    ('sweden', 'svg', 'sweden.svg'),
    ('switzerland', 'svg', 'switzerland.svg'),
    ('syria', 'svg', 'syria.svg'),
    ('tajikistan', 'svg', 'tajikistan.svg'),
    ('tanzania', 'svg', 'tanzania.svg'),
    ('thailand', 'svg', 'thailand.svg'),
    ('the_bahamas', 'svg', 'the_bahamas.svg'),
    ('the_cayman_islands', 'svg', 'the_cayman_islands.svg'),
    ('the_central_african_republic', 'svg', 'the_central_african_republic.svg'),
    ('the_czech_republic', 'svg', 'the_czech_republic.svg'),
    ('democratic_republic_of_the_congo', 'svg', 'democratic_republic_of_the_congo.svg'),
    ('the_dominican_republic', 'svg', 'the_dominican_republic.svg'),
    ('the_falkland_islands', 'svg', 'the_falkland_islands.svg'),
    ('faroe_islands', 'svg', 'faroe_islands.svg'),
    ('the_gambia', 'svg', 'the_gambia.svg'),
    ('the_isle_of_man', 'svg', 'the_isle_of_man.svg'),
    ('the_netherlands_antilles', 'svg', 'the_netherlands_antilles.svg'),
    ('the_peoples_republic_of_china', 'svg', 'the_peoples_republic_of_china.svg'),
    ('the_philippines', 'svg', 'the_philippines.svg'),
    ('the_presidency_of_turkey', 'svg', 'the_presidency_of_turkey.svg'),
    ('the_russian_federation', 'svg', 'the_russian_federation.svg'),
    ('the_solomon_islands', 'svg', 'the_solomon_islands.svg'),
    ('the_united_arab_emirates', 'svg', 'the_united_arab_emirates.svg'),
    ('tonga', 'svg', 'tonga.svg'),
    ('trinidad_and_tobago', 'svg', 'trinidad_and_tobago.svg'),
    ('tunisia', 'svg', 'tunisia.svg'),
    ('turkmenistan', 'svg', 'turkmenistan.svg'),
    ('tuvalu', 'svg', 'tuvalu.svg'),
    ('uganda', 'svg', 'uganda.svg'),
    ('ukraine', 'svg', 'ukraine.svg'),
    ('united_kingdom', 'svg', 'united_kingdom.svg'),
    ('united_states', 'svg', 'united_states.svg'),
    ('uruguay', 'svg', 'uruguay.svg'),
    ('uzbekistan', 'svg', 'uzbekistan.svg'),
    ('vanuatu', 'svg', 'vanuatu.svg'),
    ('venezuela', 'svg', 'venezuela.svg'),
    ('vietnam', 'svg', 'vietnam.svg'),
    ('yemen', 'svg', 'yemen.svg'),
    ('zambia', 'svg', 'zambia.svg'),
    ('zimbabwe', 'svg', 'zimbabwe.svg');



/* Coat_Of_Arms inserts */
INSERT INTO Coat_Of_Arm(name, type, url)
VALUES
    ('argentina', 'svg', 'argentina.svg'),
    ('afghanistan', 'svg', 'afghanistan.svg'),
    ('albania', 'svg', 'albania.svg'),
    ('algeria', 'svg', 'algeria.svg'),
    ('angola', 'svg', 'angola.svg'),
    ('armenia', 'svg', 'armenia.svg'),
    ('aruba', 'svg', 'aruba.svg'),
    ('australia', 'svg', 'australia.svg'),
    ('azerbaijan', 'svg', 'azerbaijan.svg'),
    ('bahrain', 'svg', 'bahrain.svg'),
    ('bangladesh', 'svg', 'bangladesh.svg'),
    ('barbados', 'svg', 'barbados.svg'),
    ('belarus', 'svg', 'belarus.svg'),
    ('belize', 'svg', 'belize.svg'),
    ('benin', 'svg', 'benin.svg'),
    ('bermuda', 'svg', 'bermuda.svg'),
    ('bhutan', 'svg', 'bhutan.svg'),
    ('bolivia', 'svg', 'bolivia.svg'),
    ('bosnia_and_herzegovina', 'svg', 'bosnia_and_herzegovina.svg'),
    ('botswana', 'svg', 'botswana.svg'),
    ('brazil', 'svg', 'brazil.svg'),
    ('brunei', 'svg', 'brunei.svg'),
    ('bulgaria', 'svg', 'bulgaria.svg'),
    ('burundi', 'svg', 'burundi.svg'),
    ('cambodia', 'svg', 'cambodia.svg'),
    ('canada', 'svg', 'canada.svg'),
    ('cape_verde', 'svg', 'cape_verde.svg'),
    ('chile', 'svg', 'chile.svg'),
    ('coat_of_arms', 'svg', 'coat_of_arms.svg'),
    ('colombia', 'svg', 'colombia.svg'),
    ('comoros', 'svg', 'comoros.svg'),
    ('costa_rica', 'svg', 'costa_rica.svg'),
    ('croatia', 'svg', 'croatia.svg'),
    ('cuba', 'svg', 'cuba.svg'),
    ('denmark', 'svg', 'denmark.svg'),
    ('djibouti', 'svg', 'djibouti.svg'),
    ('egypt', 'svg', 'egypt.svg'),
    ('el_salvador', 'svg', 'el_salvador.svg'),
    ('england', 'svg', 'england.svg'),
    ('eritrea', 'svg', 'eritrea.svg'),
    ('eswatini', 'svg', 'eswatini.svg'),
    ('ethiopia', 'svg', 'ethiopia.svg'),
    ('europe', 'svg', 'europe.svg'),
    ('fiji', 'svg', 'fiji.svg'),
    ('french_polynesia', 'svg', 'french_polynesia.svg'),
    ('georgia', 'svg', 'georgia.svg'),
    ('ghana', 'svg', 'ghana.svg'),
    ('gibraltar', 'svg', 'gibraltar.svg'),
    ('grenada', 'svg', 'grenada.svg'),
    ('guatemala', 'svg', 'guatemala.svg'),
    ('guernsey', 'svg', 'guernsey.svg'),
    ('guinea', 'svg', 'guinea.svg'),
    ('guyana', 'svg', 'guyana.svg'),
    ('haiti', 'svg', 'haiti.svg'),
    ('honduras', 'svg', 'honduras.svg'),
    ('hong_kong', 'svg', 'hong_kong.svg'),
    ('hungary', 'svg', 'hungary.svg'),
    ('iceland', 'svg', 'iceland.svg'),
    ('india', 'svg', 'india.svg'),
    ('indonesia_garuda_pancasila', 'svg', 'indonesia_garuda_pancasila.svg'),
    ('international_monetary_fund_logo', 'svg', 'international_monetary_fund_logo.svg'),
    ('iran', 'svg', 'iran.svg'),
    ('iraq', 'svg', 'iraq.svg'),
    ('israel_alternative', 'svg', 'israel_alternative.svg'),
    ('jamaica', 'svg', 'jamaica.svg'),
    ('japan', 'svg', 'japan.svg'),
    ('jersey', 'svg', 'jersey.svg'),
    ('jordan', 'svg', 'jordan.svg'),
    ('kazakhstan', 'svg', 'kazakhstan.svg'),
    ('kenya', 'svg', 'kenya.svg'),
    ('kiribati', 'svg', 'kiribati.svg'),
    ('kuwait', 'svg', 'kuwait.svg'),
    ('kyrgyzstan', 'svg', 'kyrgyzstan.svg'),
    ('laos', 'svg', 'laos.svg'),
    ('lebanon', 'svg', 'lebanon.svg'),
    ('lesotho', 'svg', 'lesotho.svg'),
    ('liberia', 'svg', 'liberia.svg'),
    ('libya', 'svg', 'libya.svg'),
    ('macau', 'svg', 'macau.svg'),
    ('madagascar', 'svg', 'madagascar.svg'),
    ('malawi', 'svg', 'malawi.svg'),
    ('malaysia', 'svg', 'malaysia.svg'),
    ('maldives', 'svg', 'maldives.svg'),
    ('mauritania', 'svg', 'mauritania.svg'),
    ('mauritius', 'svg', 'mauritius.svg'),
    ('mexico', 'svg', 'mexico.svg'),
    ('moldova', 'svg', 'moldova.svg'),
    ('mongolia', 'svg', 'mongolia.svg'),
    ('morocco', 'svg', 'morocco.svg'),
    ('mozambique', 'svg', 'mozambique.svg'),
    ('myanmar', 'svg', 'myanmar.svg'),
    ('namibia', 'svg', 'namibia.svg'),
    ('nepal', 'svg', 'nepal.svg'),
    ('new_zealand', 'svg', 'new_zealand.svg'),
    ('nicaragua', 'svg', 'nicaragua.svg'),
    ('nigeria', 'svg', 'nigeria.svg'),
    ('north_macedonia', 'svg', 'north_macedonia.svg'),
    ('norway', 'svg', 'norway.svg'),
    ('oman', 'svg', 'oman.svg'),
    ('papua_new_guinea', 'svg', 'papua_new_guinea.svg'),
    ('pakistan', 'svg', 'pakistan.svg'),
    ('panama', 'svg', 'panama.svg'),
    ('paraguay', 'svg', 'paraguay.svg'),
    ('per', 'svg', 'per.svg'),
    ('polski', 'svg', 'polski.svg'),
    ('qatar', 'svg', 'qatar.svg'),
    ('romania', 'svg', 'romania.svg'),
    ('rwanda', 'svg', 'rwanda.svg'),
    ('saint_helena', 'svg', 'saint_helena.svg'),
    ('samoa', 'svg', 'samoa.svg'),
    ('saudi_arabia', 'svg', 'saudi_arabia.svg'),
    ('serbia', 'svg', 'serbia.svg'),
    ('seychelles', 'svg', 'seychelles.svg'),
    ('sierra_leone', 'svg', 'sierra_leone.svg'),
    ('singapore', 'svg', 'singapore.svg'),
    ('somalia', 'svg', 'somalia.svg'),
    ('south_africa_heraldic', 'svg', 'south_africa_heraldic.svg'),
    ('south_korea', 'svg', 'south_korea.svg'),
    ('south_sudan', 'svg', 'south_sudan.svg'),
    ('so_tom_and_prncipe', 'svg', 'so_tom_and_prncipe.svg'),
    ('sri_lanka', 'svg', 'sri_lanka.svg'),
    ('sudan', 'svg', 'sudan.svg'),
    ('suriname', 'svg', 'suriname.svg'),
    ('sweden', 'svg', 'sweden.svg'),
    ('switzerland', 'svg', 'switzerland.svg'),
    ('syria', 'svg', 'syria.svg'),
    ('tajikistan', 'svg', 'tajikistan.svg'),
    ('tanzania', 'svg', 'tanzania.svg'),
    ('thailand', 'svg', 'thailand.svg'),
    ('the_bahamas', 'svg', 'the_bahamas.svg'),
    ('the_cayman_islands', 'svg', 'the_cayman_islands.svg'),
    ('the_central_african_republic', 'svg', 'the_central_african_republic.svg'),
    ('the_czech_republic', 'svg', 'the_czech_republic.svg'),
    ('democratic_republic_of_the_congo', 'svg', 'democratic_republic_of_the_congo.svg'),
    ('the_dominican_republic', 'svg', 'the_dominican_republic.svg'),
    ('the_falkland_islands', 'svg', 'the_falkland_islands.svg'),
    ('faroe_islands', 'svg', 'faroe_islands.svg'),
    ('the_gambia', 'svg', 'the_gambia.svg'),
    ('the_isle_of_man', 'svg', 'the_isle_of_man.svg'),
    ('the_netherlands_antilles', 'svg', 'the_netherlands_antilles.svg'),
    ('the_peoples_republic_of_china', 'svg', 'the_peoples_republic_of_china.svg'),
    ('the_philippines', 'svg', 'the_philippines.svg'),
    ('the_presidency_of_turkey', 'svg', 'the_presidency_of_turkey.svg'),
    ('the_russian_federation', 'svg', 'the_russian_federation.svg'),
    ('the_solomon_islands', 'svg', 'the_solomon_islands.svg'),
    ('the_united_arab_emirates', 'svg', 'the_united_arab_emirates.svg'),
    ('the_united_states_obverse', 'svg', 'the_united_states_obverse.svg'),
    ('tonga', 'svg', 'tonga.svg'),
    ('trinidad_and_tobago', 'svg', 'trinidad_and_tobago.svg'),
    ('tunisia', 'svg', 'tunisia.svg'),
    ('turkmenistan', 'svg', 'turkmenistan.svg'),
    ('tuvalu', 'svg', 'tuvalu.svg'),
    ('uganda', 'svg', 'uganda.svg'),
    ('ukraine', 'svg', 'ukraine.svg'),
    ('united_kingdom', 'svg', 'united_kingdom.svg'),
    ('united_states', 'svg', 'united_states.svg'),
    ('uruguay', 'svg', 'uruguay.svg'),
    ('uzbekistan', 'svg', 'uzbekistan.svg'),
    ('vanuatu', 'svg', 'vanuatu.svg'),
    ('venezuela', 'svg', 'venezuela.svg'),
    ('vietnam', 'svg', 'vietnam.svg'),
    ('yemen', 'svg', 'yemen.svg'),
    ('zambia', 'svg', 'zambia.svg'),
    ('zimbabwe', 'svg', 'zimbabwe.svg');



/* Countries insert */
INSERT INTO Country(
    name, official_name, abbr, internet_tld, motto, anthem, capital, official_language,
    population, iso_3166_1_alpha_2, iso_3166_1_alpha_3, calling_code, timezone,
    id_coat_of_arm, id_flag, id_currency, id_date_format, id_region, id_sub_region
) VALUES
    ('Argentina', 'Argentine Republic', 'ARG', '.ar', 'En unión y libertad', 'Himno Nacional Argentino', 'Buenos Aires', 'Spanish', 46621847, 'AR', 'ARG', '+54', 'UTC-3', 1, 1, 1, 1, 1, 1),
    ('The United Arab Emirates', 'The United Arab Emirates', 'UAE', '.ae', 'Dios, Nación, Presidente', 'Long Live My Country', 'Abu Dhabi', 'Arabic', 9516871, 'AE', 'ARE', '+971', 'UTC+4', 144, 144, 2, 2, 1, 10),
    ('Afganistán', 'Islamic Emirate of Afghanistan', 'AFN', '.af', 'No hay otro Dios más que Alá; Mahoma es el mensajero de Alá', 'This Is the Home of the Brave', 'Kabul', 'Pashto', 42239854, 'AF', 'AFG', '+93', 'UTC+4:30', 2, 2, 3, 1, 2, 5),
    ('Albania', 'Republic of Albania', 'ALB', '.al', 'You Albania, give me honour, you give me the name Albanian', 'Hymn to the Flag', 'Tirana', 'Albanian', 2832439, 'AL', 'ALB', '+355', 'UTC+1', 3, 3, 4, 1, 4, 18),
    ('Armenia', 'Republic of Armenia', 'ARM', '.am', 'One nation, one culture', 'Our Fatherland', 'Yerevan', 'Armenian', 2998500, 'AM', 'ARM', '+374', 'UTC+4', 6, 6, 8, 1, 2, 9),
    ('The Netherlands Antilles', 'The Netherlands Antilles', 'ANT', '.an', 'Unified in freedom', 'Anthem without a title', 'Willemstad', 'Dutch', 151066, 'AN', 'ANT', '+599', 'UTC-4', 138, 138, 70, 1, 1, 2),
    ('Angola', 'Republic of Angola', 'AO', '.ao', 'Virtue is stronger when united', 'Onwards Angola', 'Luanda', 'Kimbundu', 36684202, 'AO', 'AGO', '+244', 'UTC+1', 5, 5, 7, 1, 3, 14),
    ('Australia', 'Commonwealth of Australia', 'AUS', '.au', '-', 'Advance Australia Fair', 'Canberra', 'English', 26439111, 'AU', 'AUS', '+61', 'UTC+11', 8, 8, 9, 1, 5, 20),
    ('Aruba', 'Country of Aruba', 'ABW', '.aw', '-', 'Aruba Dushi Tera', 'Oranjestad', 'Papiamento', 106277, 'AW', 'ABW', '+297', 'UTC-4', 7, 7, 46, 1, 1, 2),
    ('Azerbaijan', 'Republic of Azerbaijan', 'AZE', '.az', '-', 'March of Azerbaijan', 'Baku', 'Azerbaijani', 10412651, 'AZ', 'AZE', '+994', 'UTC+4', 9, 9, 10, 1, 2, 9),
    ('Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BIH', '.ba', 'One land, three people, nine names', 'National Anthem of Bosnia and Herzegovina', 'Sarajevo', 'Latin', 3210847, 'BA', 'BIH', '+387', 'UTC+1', 19, 19, 18, 2, 4, 16),
    ('Barbados', 'Barbados', 'BRB', '.bb', 'Pride and Industry', 'In Plenty and In Time of Need', 'Bridgetown', 'English', 281995, 'BB', 'BRB', '+1246', 'UTC-4', 12, 12, 13, 2, 1, 2),
    ('Bangladesh', 'People''s Republic of Bangladesh', 'BAN', '.bd', 'Joy Bangla', 'My Golden Bengal', 'Dhaka', 'Bengali', 172954319, 'BD', 'BGD', '+880', 'UTC+6', 11, 11, 12, 2, 2, 8),
    ('Bulgaria', 'Republic of Bulgaria', 'BGR', '.bg', 'Unity makes strength', 'Unity makes strength', 'Sofia', 'Bulgarian', 6687717, 'BG', 'BGR', '+359', 'UTC+2', 23, 23, 23, 2, 4, 16),
    ('Bahrain', 'Kingdom of Bahrain', 'BHR', '.bh', '-', 'Our Bahrain', 'Manama', 'Arabic', 1485509, 'BH', 'BHR', '+973', 'UTC+3', 10, 10, 11, 2, 2, 9),
    ('Burundi', 'Republic of Burundi', 'BDI', '.bi', 'Unity, Work, Progress', 'L''Hymne du Burundi', 'Gitega', 'Kirundi, French', 13238559, 'BI', 'BDI', '+257', 'UTC+2', 24, 24, 24, 3, 3, 12),
    ('Bermuda', 'Bermuda', 'BMU', '.bm', 'Quo Fata Ferunt', 'God Save the King', 'Hamilton', 'English', 64019, 'BM', 'BMU', '+1441', 'UTC-4', 16, 16, 47, 1, 1, 2),
    ('Brunei', 'Brunei Darussalam', 'BRN', '.bn', 'Selalu dalam Bimbingan Allah', 'Allah Pemelihara Sultan', 'Bandar Seri Begawan', 'Malay', 452523, 'BN', 'BRN', '+673', 'UTC+8', 22, 22, 22, 2, 2, 7),
    ('Bolivia', 'Plurinational State of Bolivia', 'BOL', '.bo', 'Libertad, Igualdad, Fraternidad', 'Himno Nacional de Bolivia', 'La Paz', 'Spanish', 12440603, 'BO', 'BOL', '+591', 'UTC-4', 18, 18, 17, 3, 3, 1),
    ('Brazil', 'Federative Republic of Brazil', 'BRA', '.br', 'Ordem e Progresso', 'Order and Progress', 'Brasilia', 'Portuguese', 216422446, 'BR', 'BRA', '+55', 'UTC+3', 21, 21, 20, 3, 3, 1),
    ('Bahamas', 'Commonwealth of The Bahamas', 'BHS', '.bs', 'Forward, Upward, Onward Together', 'March On, Bahamaland', 'Nassau', 'English', 412623, 'BS', 'BHS', '+1242', 'UTC-5', 128, 128, 63, 1, 1, 2),
    ('Bhutan', 'Kingdom of Bhutan', 'BTN', '.bt', 'The Dragon Kingdom', 'Druk tsendhen', 'Thimphu', 'Dzongkha', 784114, 'BT', 'BTN', '+975', 'UTC+5:30', 17, 17, 16, 2, 2, 8),
    ('Botswana', 'Republic of Botswana', 'BWA', '.bw', 'Pula', 'Fatshe leno la rona', 'Gaborone', 'Setswana', 2410336, 'BW', 'BWA', '+267', 'UTC+2', 20, 20, 19, 2, 3, 14),
    ('Belarus', 'Republic of Belarus', 'BLR', '.by', 'We, the Belarusian people', 'My Belarusy', 'Minsk', 'Belarusian, Russian', 9463234, 'BY', 'BLR', '+375', 'UTC+3', 13, 13, 14, 3, 4, 16),
    ('Belize', 'Belize', 'BLZ', '.bz', 'Sub umbra floreo', 'Land of the Free', 'Belmopan', 'English', 430322, 'BZ', 'BLZ', '+501', 'UTC-6', 14, 14, 15, 1, 1, 3),
    ('Canada', 'Dominion of Canada', 'CAN', '.ca', 'A Mari Usque Ad Mare', 'O Canada', 'Ottawa', 'English and French', 0, 'CA', 'CAN', '+1', 'UTC', 26, 26, 26, 1, 1, 4),
    ('Democratic Republic of the Congo', 'République démocratique du Congo', 'COD', '.cd', 'Justice – Paix – Travail', 'Debout Congolais', 'Kinshasa', 'French', 0, 'CD', 'COD', '+243', 'UTC', 132, 132, 37, 1, 2, 13),
    ('Switzerland', 'Swiss Confederation', 'CHE', '.ch', 'Unus pro omnibus, omnes pro uno', 'Swiss Psalm', 'Bern', 'German', 0, 'CH', 'CHE', '+41', 'UTC', 123, 123, 142, 2, 4, 19),
    ('Chile', 'Republic of Chile', 'CHL', '.cl', 'Por la razón o la fuerza', 'Canción Nacional', 'Santiago', 'Spanish', 0, 'CL', 'CHL', '+56', 'UTC', 28, 28, 28, 3, 3, 1),
    ('China', "People's Republic of China", 'CHN', '.cn', 'Serve the people', 'March of the Volunteers', 'Beijing', 'Mandarin', 0, 'CN', 'CHN', '+86', 'UTC+8', 139, 139, 29, 2, 2, 6),
    ('Colombia', 'Republic of Colombia', 'COL', '.co', 'Libertad y Orden', 'Himno Nacional de la República de Colombia', 'Bogotá', 'Spanish', 0, 'CO', 'COL', '+57', 'UTC', 30, 30, 30, 3, 3, 1),
    ('Cuba', 'Republic of Cuba', 'CUB', '.cu', 'Patria o Muerte, Venceremos', 'La Bayamesa', 'Havana', 'Spanish', 0, 'CU', 'CUB', '+53', 'UTC', 34, 34, 34, 1, 1, 2),
    ('Costa Rica', 'Republic of Costa Rica', 'CRI', '.cr', 'Vivan siempre el trabajo y la paz', 'Himno Nacional de Costa Rica', 'San José', 'Spanish', 0, 'CR', 'CRI', '+506', 'UTC', 32, 32, 32, 1, 1, 3),
    ('Cape Verde', 'Republic of Cabo Verde', 'CV', '.cv', 'Unidade, Trabalho, Progresso', 'Cântico da Liberdade', 'Praia', 'Portuguese', 0, 'CV', 'CPV', '+238', 'UTC', 27, 27, 48, 1, 3, 15),
    ('Czech Republic', 'Czech Republic', 'CZ', '.cz', 'Pravda vítězí', 'Kde domov můj', 'Prague', 'Czech', 0, 'CZ', 'CZE', '+420', 'UTC', 131, 131, 35, 1, 4, 16),
    ('Djibouti', 'Republic of Djibouti', 'DJ', '.dj', 'Unité, Égalité, Paix', 'We arise with strength! for we have raised our flag', 'Djibouti City', 'Arabic, French', 0, 'DJ', 'DJI', '+253', 'UTC', 36, 36, 38, 1, 3, 12),
    ('Denmark', 'Kingdom of Denmark', 'DK', '.dk', 'Guds hjælp, Folkets kærlighed, Danmarks styrke', 'Der er et yndigt land', 'Copenhagen', 'Danish', 0, 'DK', 'DNK', '+45', 'UTC', 35, 35, 36, 1, 4, 17),
    ('Dominican Republic', 'Dominican Republic', 'DO', '.do', 'Dios, Patria, Libertad', 'Himno Nacional', 'Santo Domingo', 'Spanish', 0, 'DO', 'DOM', '+1-809', 'UTC', 133, 133, 39, 1, 1, 2),
    ('Algeria', "People's Democratic Republic of Algeria", 'DZ', '.dz', 'By the people and for the people', 'Kassaman', 'Algiers', 'Arabic, Berber', 0, 'DZ', 'DZA', '+213', 'UTC', 4, 4, 5, 3, 3, 11),
    ('Egypt', 'Arab Republic of Egypt', 'EG', '.eg', 'Ankh, Ujat, Seneb', 'Eslami ya Misr', 'Cairo', 'Arabic', 0, 'EG', 'EGY', '+20', 'UTC', 37, 37, 41, 3, 3, 11),
    ('Eritrea', 'State of Eritrea', 'ER', '.er', '-', 'Ertra, Ertra, Ertra', 'Asmara', 'Tigrinya', 3612706, 'ER', 'ERI', '+291', 'UTC+3', 40, 40, 42, 3, 3, 12),
    ('Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ET', '.et', '-', 'Wenchi Neh Ena Sileste', 'Addis Ababa', 'Amharic', 127110000, 'ET', 'ETH', '+251', 'UTC+3', 42, 42, 43, 3, 3, 12),
    ('European Union', '', '', '.eu', '', '', '', '', 0, '', '', 0, 'UTC', NULL, NULL, 40, NULL, NULL, NULL),
    ('Fiji', 'Republic of Fiji', 'FJ', '.fj', 'Fiji, the Way the World Begins', 'God Bless Fiji', 'Suva', 'English', 1013952, 'FJ', 'FJI', '+679', 'UTC+12', 44, 44, 44, 2, 5, 23),
    ('Falkland Islands', 'Falkland Islands', 'FK', '.fk', 'Desire the right', 'God Save the Queen', 'Stanley', 'English', 3500, 'FK', 'FLK', '+500', 'UTC-4', 134, 134, 65, 1, 1, 1),
    ('Faroe Islands', 'Føroyar', 'FO', '.fo', '', 'Tú alfagra land mítt', 'Tórshavn', 'Faroese', 54987, 'FO', 'FRO', '+298', 'UTC+0', 137, 137, 66, 1, 4, 17),
    ('United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'UK', '.uk', 'Dieu et mon droit', 'God Save the Queen', 'London', 'English', 67545757, 'GB', 'GBR', '+44', 'UTC', 154, 154, 21, 1, 4, 17),
    ('Georgia', 'Georgia', 'GE', '.ge', 'Strength in Unity', 'Tavisupleba', 'Tbilisi', 'Georgian', 3912083, 'GE', 'GEO', '+995', 'UTC+4', 46, 46, 73, 2, 2, 9),
    ('Guernsey', 'Bailiwick of Guernsey', 'GG', '.gg', 'Dieu est mon droit', 'God Save the Queen', 'St. Peter Port', 'English', 67523, 'GG', 'GGY', '+44', 'UTC+0', 51, 51, 52, 1, 4, 17),
    ('Ghana', 'Republic of Ghana', 'GH', '.gh', 'Freedom and Justice', 'God Bless Our Homeland Ghana', 'Accra', 'English', 34032000, 'GH', 'GHA', '+233', 'UTC', 47, 47, 74, 1, 3, 15),
    ('Gibraltar', 'Gibraltar', 'GI', '.gi', 'NULLIUS IN VERBA', 'God Save the Queen', 'Gibraltar', 'English', 34000, 'GI', 'GIB', '+350', 'UTC+1', 48, 48, 68, 1, 4, 19),
    ('The Gambia', 'Republic of The Gambia', 'GM', '.gm', 'Progress, Peace, Prosperity', 'For Gambia Our Homeland', 'Banjul', 'English', 2539384, 'GM', 'GMB', '+220', 'UTC+0', 136, 136, 67, 1, 3, 15),
    ('Guinea', 'Republic of Guinea', 'GN', '.gn', 'Work, Justice, Solidarity', 'Liberté', 'Conakry', 'French', 13533533, 'GN', 'GIN', '+224', 'UTC', 52, 52, 76, 1, 3, 15),
    ('Guatemala', 'Republic of Guatemala', 'GT', '.gt', 'Libre Crezca Fecundo', 'Guatemala Feliz', 'Guatemala City', 'Spanish', 18585000, 'GT', 'GTM', '+502', 'UTC-6', 50, 50, 75, 1, 3, 3),
    ('Guyana', 'Co-operative Republic of Guyana', 'GY', '.gy', 'One People, One Nation, One Destiny', 'Dear Land of Guyana, of Rivers and Plains', 'Georgetown', 'English', 809200, 'GY', 'GUY', '+592', 'UTC-4', 53, 53, 77, 1, 1, 1),
    ('Hong Kong', "Hong Kong Special Administrative Region of the People's Republic of China", 'HK', '.hk', '', 'March of the Volunteers', 'Central', 'Chinese (Traditional)', 7552500, 'HK', 'HKG', '+852', 'UTC+8', 56, 56, 71, 2, 6, 6),
    ('Honduras', 'Republic of Honduras', 'HN', '.hn', 'Libre, Soberana e Independiente', 'Himno Nacional de Honduras', 'Tegucigalpa', 'Spanish', 10902000, 'HN', 'HND', '+504', 'UTC-6', 55, 55, 79, 1, 3, 3),
    ('Croatia', 'Republic of Croatia', 'HR', '.hr', 'Za dom spremni', 'Lijepa naša domovino', 'Zagreb', 'Croatian', 4108800, 'HR', 'HRV', '+385', 'UTC+1', 33, 33, 33, 1, 4, 18),
    ('Haiti', 'Republic of Haiti', 'HT', '.ht', "L'Union Fait la Force", 'La Dessalinienne', 'Port-au-Prince', 'French', 12648000, 'HT', 'HTI', '+509', 'UTC-5', 54, 54, 78, 1, 1, 3),
    ('Indonesia', 'Republic of Indonesia', 'ID', '.id', 'Bhinneka Tunggal Ika', 'Indonesia Raya', 'Jakarta', 'Indonesian', 283672915, 'ID', 'IDN', '+62', 'UTC+7', 60, 60, 84, 2, 5, 2),
    ('Israel', 'State of Israel', 'IL', '.il', '', 'Hatikvah', 'Jerusalem', 'Hebrew', 9582000, 'IL', 'ISR', '+972', 'UTC+2', 64, 64, 87, 2, 2, 10),
    ('Isle of Man', 'Isle of Man', 'IM', '.im', 'Quocunque Jeceris Stabit', 'Arrane Ashoonagh dy Vannin', 'Douglas', 'English', 85424, 'IM', 'IMN', '+44', 'UTC+0', 137, 137, 69, 1, 4, 17),
    ('India', 'Republic of India', 'IN', '.in', 'Satyameva Jayate', 'Jana Gana Mana', 'New Delhi', 'Hindi', 1444215000, 'IN', 'IND', '+91', 'UTC+5:30', 59, 59, 83, 2, 2, 8),
    ('Iraq', 'Republic of Iraq', 'IQ', '.iq', '', 'Mawtini', 'Baghdad', 'Arabic', 41147072, 'IQ', 'IRQ', '+964', 'UTC+3', 63, 63, 86, 2, 2, 10),
    ('Iran', 'Islamic Republic of Iran', 'IR', '.ir', 'Independence, Freedom, Islamic Republic', 'Sorood-e Melli-e Jomhouri-e Eslami', 'Tehran', 'Persian', 89255483, 'IR', 'IRN', '+98', 'UTC+3:30', 62, 62, 85, 2, 2, 10),
    ('Iceland', 'Republic of Iceland', 'IS', '.is', '', 'Lofsöngur', 'Reykjavik', 'Icelandic', 371530, 'IS', 'ISL', '+354', 'UTC', 58, 58, 81, 1, 4, 17),
    ('Jersey', 'Bailiwick of Jersey', 'JE', '.je', '', 'God Save the Queen', 'Saint Helier', 'English', 100800, 'JE', 'JEY', '+44', 'UTC+1', 66, 66, 53, 1, 4, 17),
    ('Jamaica', 'Jamaica', 'JM', '.jm', 'Out of Many, One People', 'Jamaica, Land We Love', 'Kingston', 'English', 2961161, 'JM', 'JAM', '+1876', 'UTC-5', 65, 65, 88, 3, 1, 2),
    ('Jordan', 'Hashemite Kingdom of Jordan', 'JO', '.jo', '', 'Al-Salam Al-Malaki Al-Urdoni', 'Amman', 'Arabic', 11040505, 'JO', 'JOR', '+962', 'UTC+2', 67, 67, 90, 3, 3, 10),
    ('Japan', 'Japan', 'JP', '.jp', '', 'Kimigayo', 'Tokyo', 'Japanese', 125474293, 'JP', 'JPN', '+81', 'UTC+9', 66, 66, 89, 2, 2, 6),
    ('Kenya', 'Republic of Kenya', 'KE', '.ke', 'Harambee', 'Ee Mungu Nguvu Yetu', 'Nairobi', 'English, Swahili', 58058156, 'KE', 'KEN', '+254', 'UTC+3', 69, 69, 92, 3, 3, 12),
    ('Kyrgyzstan', 'Kyrgyz Republic', 'KG', '.kg', '', 'Kyrgyz Respublikasynyn Mamlekettik Gimni', 'Bishkek', 'Kyrgyz, Russian', 6746407, 'KG', 'KGZ', '+996', 'UTC+6', 72, 72, 95, 2, 2, 5),
    ('Cambodia', 'Kingdom of Cambodia', 'KH', '.kh', '', 'Nokor Reach', 'Phnom Penh', 'Khmer', 17134623, 'KH', 'KHM', '+855', 'UTC+7', 25, 25, 25, 2, 2, 7),
    ('Kiribati', 'Republic of Kiribati', 'KI', '.ki', 'Te mauri, te raoi, te tabomoa', 'Te Ira Kiribati', 'Tarawa Atoll', 'I-Kiribati, English', 123380, 'KI', 'KIR', '+686', 'UTC+12', 70, 70, 93, 1, 5, 20),
    ('Comoros', 'Union of the Comoros', 'KM', '.km', 'Umoja, Ndugu, Amani', 'Udzima wa ya Masiwa', 'Moroni', 'Arabic, Comorian, French', 911392, 'KM', 'COM', '+269', 'UTC+3', 30, 30, 31, 2, 2, 12),
    ('South Korea', 'Republic of Korea', 'KR', '.kr', '', 'Aegukga', 'Seoul', 'Korean', 51848577, 'KR', 'KOR', '+82', 'UTC+9', 116, 116, 136, 2, 2, 6),
    ('Kuwait', 'State of Kuwait', 'KW', '.kw', '', 'Allah Akbar', 'Kuwait City', 'Arabic', 4467757, 'KW', 'KWT', '+965', 'UTC+3', 71, 71, 94, 2, 2, 10),
    ('Cayman Islands', 'Cayman Islands', 'KY', '.ky', '', 'God Save the Queen', 'George Town', 'English', 68076, 'KY', 'KYM', '+1345', 'UTC-5', 129, 129, 64, 1, 5, 2),
    ('Kazakhstan', 'Republic of Kazakhstan', 'KZ', '.kz', '', 'Menin Qazaqstanim', 'Nur Sultan', 'Kazakh, Russian', 19533388, 'KZ', 'KAZ', '+7', 'UTC+6', 69, 69, 91, 2, 2, 5),
    ('Laos', "Lao People's Democratic Republic", 'LA', '.la', '', 'Xat Lao', 'Vientiane', 'Lao', 7544544, 'LA', 'LAO', '+856', 'UTC+7', 73, 73, 96, 2, 2, 7),
    ('Lebanon', 'Lebanese Republic', 'LB', '.lb', '', 'Biladi, Biladi, Biladi', 'Beirut', 'Arabic', 6849391, 'LB', 'LBN', '+961', 'UTC+2', 74, 74, 97, 2, 2, 10),
    ('Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'LK', '.lk', '', 'Namo Namo Matha', 'Sri Jayawardenapura Kotte', 'Sinhala', 22059300, 'LK', 'LKA', '+94', 'UTC+5:30', 119, 119, 138, 2, 2, 8),
    ('Liberia', 'Republic of Liberia', 'LR', '.lr', 'The Love of Liberty Brought Us Here', 'All Hail Liberia Hail', 'Monrovia', 'English', 5313373, 'LR', 'LBR', '+231', 'UTC', 76, 76, 98, 3, 3, 15),
    ('Lesotho', 'Kingdom of Lesotho', 'LS', '.ls', '', 'Lesotho Fatse La Bontata Rona', 'Maseru', 'English, Sesotho', 2353404, 'LS', 'LSO', '+266', 'UTC+2', 75, 75, 54, 3, 3, 14),
    ('Libya', 'State of Libya', 'LY', '.ly', '', 'Allahu Akbar', 'Tripoli', 'Arabic', 6936934, 'LY', 'LBY', '+218', 'UTC+2', 77, 77, 99, 3, 3, 11),
    ('Morocco', 'Kingdom of Morocco', 'MA', '.ma', '', 'Ash-Sharif al-Alaoui', 'Rabat', 'Arabic', 37610000, 'MA', 'MAR', '+212', 'UTC', 88, 88, 109, 3, 3, 11),
    ('Moldova', 'Republic of Moldova', 'MD', '.md', '', 'Limba Noastră', 'Chișinău', 'Romanian', 4056900, 'MD', 'MDA', '+373', 'UTC+2', 86, 86, 56, 2, 4, 16),
    ('Madagascar', 'Republic of Madagascar', 'MG', '.mg', '', 'Ry Tanindrazana Malala O', 'Antananarivo', 'Malagasy', 29107500, 'MG', 'MDG', '+261', 'UTC+3', 79, 79, 100, 3, 3, 12),
    ('North Macedonia', 'Republic of North Macedonia', 'MK', '.mk', '', 'Denes nad Makedonija', 'Skopje', 'Macedonian', 2114550, 'MK', 'MKD', '+389', 'UTC+1', 97, 97, 59, 1, 4, 7),
    ('Myanmar', 'Republic of the Union of Myanmar', 'MM', '.mm', '', 'Kaba Ma Kyei', 'Naypyidaw', 'Burmese', 54323833, 'MM', 'MMR', '+95', 'UTC+6:30', 90, 90, 57, 2, 2, 6),
    ('Mongolia', 'Mongolia', 'MN', '.mn', '', 'Mongolyn Ündsen Ündestiin Temee Duulal', 'Ulaanbaatar', 'Mongolian', 3407300, 'MN', 'MNG', '+976', 'UTC+8', 87, 87, 108, 2, 2, 6),
    ('Macau', "Macao Special Administrative Region of the People's Republic of China", 'MO', '.mo', 'East meets West', 'A Portuguesa', 'Macau', 'Chinese', 689600, 'MO', 'MAC', '+853', 'UTC+8', 78, 78, 55, 2, 2, 15),
    ('Mauritania', 'Islamic Republic of Mauritania', 'MR', '.mr', '', 'Biladi', 'Nouakchott', 'Arabic', 4644034, 'MR', 'MRT', '+222', 'UTC', 83, 83, 105, 3, 3, 12),
    ('Mauritius', 'Republic of Mauritius', 'MU', '.mu', '', 'Stella Clavisque Maris Indici', 'Port Louis', 'English', 1271769, 'MU', 'MUS', '+230', 'UTC+4', 84, 84, 106, 1, 5, 8),
    ('Maldives', 'Republic of Maldives', 'MV', '.mv', '', 'Qaumi Salaam', 'Malé', 'Dhivehi', 580541, 'MV', 'MDV', '+960', 'UTC+5', 82, 82, 104, 2, 5, 12),
    ('Malawi', 'Republic of Malawi', 'MW', '.mw', '', 'Mulungu akudalitsa Malawi', 'Lilongwe', 'English, Chichewa', 20163431, 'MW', 'MWI', '+265', 'UTC+2', 80, 80, 102, 3, 3, 4),
    ('Mexico', 'United Mexican States', 'MX', '.mx', '', 'Himno Nacional Mexicano', 'Mexico City', 'Spanish', 133932315, 'MX', 'MEX', '+52', 'UTC-6', 85, 85, 107, 1, 1, 7),
    ('Malaysia', 'Federation of Malaysia', 'MY', '.my', '', 'Negaraku', 'Kuala Lumpur', 'Malay', 33800000, 'MY', 'MYS', '+60', 'UTC+8', 81, 81, 103, 2, 2, 12),
    ('Mozambique', 'Republic of Mozambique', 'MZ', '.mz', '', 'Pátria Amada', 'Maputo', 'Portuguese', 36024000, 'MZ', 'MOZ', '+258', 'UTC+2', 89, 89, 110, 3, 3, 12),
    ('Namibia', 'Republic of Namibia', 'NA', '.na', '', 'Namibia, Land of the Brave', 'Windhoek', 'English', 2644755, 'NA', 'NAM', '+264', 'UTC+1', 91, 91, 111, 3, 3, 14),
    ('Nigeria', 'Federal Republic of Nigeria', 'NG', '.ng', '', 'Arise, O Compatriots', 'Abuja', 'English', 225778453, 'NG', 'NGA', '+234', 'UTC+1', 95, 95, 114, 1, 3, 15),
    ('Nicaragua', 'Republic of Nicaragua', 'NI', '.ni', '', 'Salve a ti, Nicaragua', 'Managua', 'Spanish', 6850583, 'NI', 'NIC', '+505', 'UTC-6', 94, 94, 58, 1, 1, 3),
    ('Norway', 'Kingdom of Norway', 'NO', '.no', '', 'Ja, vi elsker dette landet', 'Oslo', 'Norwegian', 5425270, 'NO', 'NOR', '+47', 'UTC+1', 97, 97, 115, 1, 4, 17),
    ('Nepal', 'Federal Democratic Republic of Nepal', 'NP', '.np', '', 'Satyameva Jayate', 'Kathmandu', 'Nepali', 31551484, 'NP', 'NPL', '+977', 'UTC+5:45', 92, 92, 112, 2, 2, 8),
    ('New Zealand', 'New Zealand', 'NZ', '.nz', '', 'God Defend New Zealand', 'Wellington', 'English, Māori', 5234400, 'NZ', 'NZL', '+64', 'UTC+12', 93, 93, 113, 1, 5, 20),
    ('Oman', 'Sultanate of Oman', 'OM', '.om', '', 'Nashid al-Salam al-Sultani', 'Muscat', 'Arabic', 5467192, 'OM', 'OMN', '+968', 'UTC+4', 98, 98, 117, 2, 2, 9),
    ('Panama', 'Republic of Panama', 'PA', '.pa', '', 'Himno Nacional de la República de Panamá', 'Panama City', 'Spanish', 4448209, 'PA', 'PAN', '+507', 'UTC-5', 100, 100, 119, 1, 1, 3),
    ('Peru', 'Republic of Peru', 'PE', '.pe', '', 'Somos libres, seámoslo siempre', 'Lima', 'Spanish, Quechua, Aymara', 33609960, 'PE', 'PER', '+51', 'UTC-5', 102, 102, 122, 1, 1, 1),
    ('Papua New Guinea', 'Independent State of Papua New Guinea', 'PG', '.pg', '', 'O God, Stand Beside Us', 'Port Moresby', 'English, Tok Pisin', 9061431, 'PG', 'PNG', '+675', 'UTC+10', 100, 100, 120, 1, 5, 20),
    ('Philippines', 'Republic of the Philippines', 'PH', '.ph', '', 'Lupang Hinirang', 'Manila', 'Filipino, English', 114015954, 'PH', 'PHL', '+63', 'UTC+8', 141, 141, 45, 1, 1, 7),
    ('Pakistan', 'Islamic Republic of Pakistan', 'PK', '.pk', '', 'Qaumi Tarana', 'Islamabad', 'Urdu, English', 239692917, 'PK', 'PAK', '+92', 'UTC+5', 99, 99, 118, 1, 1, 8),
    ('Poland', 'Republic of Poland', 'PL', '.pl', '', 'Mazurek Dąbrowskiego', 'Warsaw', 'Polish', 37998639, 'PL', 'POL', '+48', 'UTC+1', 103, 103, 123, 2, 4, 16),
    ('Paraguay', 'Republic of Paraguay', 'PY', '.py', '', 'Paraguayos, República o muerte!', 'Asunción', 'Spanish, Guarani', 7307457, 'PY', 'PRY', '+595', 'UTC-4', 101, 101, 121, 1, 1, 1),
    ('Qatar', 'State of Qatar', 'QA', '.qa', '', 'As-Salam al-Amiri', 'Doha', 'Arabic', 3454234, 'QA', 'QAT', '+974', 'UTC+3', 104, 104, 124, 1, 1, 9),
    ('Romania', 'Romania', 'RO', '.ro', '', 'Deșteaptă-te, române!', 'Bucharest', 'Romanian', 19364555, 'RO', 'ROU', '+40', 'UTC+2', 105, 105, 125, 1, 4, 16),
    ('Serbia', 'Republic of Serbia', 'RS', '.rs', '', 'Bože pravde', 'Belgrade', 'Serbian', 6963764, 'RS', 'SRB', '+381', 'UTC+1', 110, 110, 131, 1, 4, 16),
    ('Russia', 'Russian Federation', 'RU', '.ru', 'Bozhe, Tsarya khrani!', 'Gosudarstvennyy Gimn Rossiyskoy Federatsii', 'Moscow', 'Russian', 146238206, 'RU', 'RUS', '+7', 'UTC+3', 142, 142, 126, 2, 2, 6),
    ('Rwanda', 'Republic of Rwanda', 'RW', '.rw', '', 'Rwanda Nziza', 'Kigali', 'Kinyarwanda, French, English', 13740000, 'RW', 'RWA', '+250', 'UTC+2', 106, 106, 127, 3, 3, 12),
    ('Saudi Arabia', 'Kingdom of Saudi Arabia', 'SA', '.sa', '', 'Long Live the King', 'Riyadh', 'Arabic', 36979471, 'SA', 'SAU', '+966', 'UTC+3', 109, 109, 130, 1, 1, 9),
    ('Solomon Islands', 'Solomon Islands', 'SB', '.sb', '', 'God Save Our Solomon Islands', 'Honiara', 'English', 721348, 'SB', 'SLB', '+677', 'UTC+11', 115, 115, 134, 1, 5, 21),
    ('Seychelles', 'Republic of Seychelles', 'SC', '.sc', '', 'Seychellois, mon pays, mon peuple', 'Victoria', 'Seychellois Creole', 98462, 'SC', 'SYC', '+248', 'UTC+4', 111, 111, 132, 1, 5, 12),
    ('Sudan', 'Republic of the Sudan', 'SD', '.sd', '', 'Biladi', 'Khartoum', 'Arabic', 45841243, 'SD', 'SDN', '+249', 'UTC+2', 120, 120, 139, 3, 3, 12),
    ('Sweden', 'Kingdom of Sweden', 'SE', '.se', '', 'Du gamla, Du fria', 'Stockholm', 'Swedish', 10478115, 'SE', 'SWE', '+46', 'UTC+1', 122, 122, 141, 2, 4, 17),
    ('Singapore', 'Republic of Singapore', 'SG', '.sg', '', 'Majulah Singapura', 'Singapore', 'English, Malay, Tamil, Chinese', 5889986, 'SG', 'SGP', '+65', 'UTC+8', 113, 113, 133, 2, 2, 7),
    ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'SH', '.sh', '', 'God Save the Queen', 'Jamestown', 'English', 4534, 'SH', 'SHN', '+290', 'UTC±0', 107, 107, 60, 1, 5, 14),
    ('Sierra Leone', 'Republic of Sierra Leone', 'SL', '.sl', '', 'High We Exalt Thee, Realm of the Free', 'Freetown', 'English', 8545386, 'SL', 'SLE', '+232', 'UTC', 112, 112, 61, 1, 5, 15),
    ('Somalia', 'Federal Republic of Somalia', 'SO', '.so', '', 'Soomaaliyaay toosoo', 'Mogadishu', 'Somali, Arabic', 16361093, 'SO', 'SOM', '+252', 'UTC+3', 114, 114, 135, 1, 1, 12),
    ('Suriname', 'Republic of Suriname', 'SR', '.sr', '', 'God zij met ons Suriname', 'Paramaribo', 'Dutch', 586388, 'SR', 'SUR', '+597', 'UTC-3', 121, 121, 140, 1, 1, 1),
    ('South Sudan', 'Republic of South Sudan', 'SS', '.ss', '', 'Juwe', 'Juba', 'English', 13082550, 'SS', 'SSD', '+211', 'UTC+2', 117, 117, 137, 1, 1, 12),
    ('São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', 'ST', '.st', '', 'Independência total', 'São Tomé', 'Portuguese', 220400, 'ST', 'STP', '+239', 'UTC', 118, 118, 129, 1, 1, 15),
    ('Syria', 'Syrian Arab Republic', 'SY', '.sy', '', 'Humat ad-Diyar', 'Damascus', 'Arabic', 17500658, 'SY', 'SYR', '+963', 'UTC+2', 124, 124, 143, 1, 1, 9),
    ('Eswatini', 'Kingdom of Eswatini', 'SZ', '.sz', '', 'Nkulunkulu Mnikati', 'Mbabana', 'English, Swati', 1164101, 'SZ', 'SWZ', '+268', 'UTC+2', 48, 48, 50, 3, 3, 14),
    ('Thailand', 'Kingdom of Thailand', 'TH', '.th', '', 'Phleng Chat', 'Bangkok', 'Thai', 70098733, 'TH', 'THA', '+66', 'UTC+7', 116, 116, 147, 2, 2, 7),
    ('Tajikistan', 'Republic of Tajikistan', 'TJ', '.tj', '', 'Surudi Milli', 'Dushanbe', 'Tajik', 9811588, 'TJ', 'TJK', '+992', 'UTC+5', 119, 119, 145, 2, 2, 5),
    ('Turkmenistan', 'Turkmenistan', 'TM', '.tm', '', 'Garaşsyz, Bitarap, Türkmenistan', 'Ashgabat', 'Turkmen', 6217371, 'TM', 'TKM', '+993', 'UTC+5', 126, 126, 151, 2, 2, 5),
    ('Tunisia', 'Republic of Tunisia', 'TN', '.tn', '', 'Humat al-Hima', 'Tunis', 'Arabic', 12130000, 'TN', 'TUN', '+216', 'UTC+1', 123, 123, 150, 1, 1, 11),
    ('Tonga', 'Kingdom of Tonga', 'TO', '.to', '', 'Ko e fasi ʻo e tuʻi ʻo e ʻOtu Tonga', 'Nukuʻalofa', 'Tongan', 105695, 'TO', 'TON', '+676', 'UTC+13', 127, 127, 148, 1, 5, 23),
    ('Turkey', 'Republic of Turkey', 'TR', '.tr', 'Sovereignty unconditionally belongs to the People', 'National Anthem', 'Ankara', 'Turkish', 86031639, 'TR', 'TUR', '+90', 'UTC+2', 128, 128, 72, 2, 4, 19),
    ('Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TT', '.tt', '', 'Together we aspire, together we achieve', 'Port of Spain', 'English', 1406467, 'TT', 'TTO', '+1868', 'UTC-4', 125, 125, 149, 1, 1, 1),
    ('Tuvalu', 'Tuvalu', 'TV', '.tv', '', 'Tuvalu mo te Atua', 'Vaiaku village', 'Tuvaluan', 11792, 'TV', 'TUV', '+688', 'UTC+12', 130, 130, 152, 1, 5, 23),
    ('Taiwan', 'Republic of China (Taiwan)', 'TW', '.tw', '', 'National Anthem of the Republic of China', 'Taipei', 'Mandarin Chinese', 23503349, 'TW', 'TWN', '+886', 'UTC+8', 129, 129, 144, 2, 2, 6),
    ('Tanzania', 'United Republic of Tanzania', 'TZ', '.tz', '', 'Mungu ibariki Afrika', 'Dar es Salaam; Dodoma', 'Swahili', 64387033, 'TZ', 'TZA', '+255', 'UTC+3', 131, 131, 146, 3, 3, 12),
    ('Ukraine', 'Ukraine', 'UA', '.ua', 'Slava Ukraini! Heroiam slava!', 'Shche ne vmerla Ukrainy i slava, i volia', 'Kyiv', 'Ukrainian', 44134695, 'UA', 'UKR', '+380', 'UTC+2', 133, 133, 154, 2, 4, 16),
    ('Uganda', 'Republic of Uganda', 'UG', '.ug', '', 'Oh Uganda, Land of Beauty', 'Kampala', 'English', 48435343, 'UG', 'UGA', '+256', 'UTC+3', 132, 132, 153, 3, 3, 12),
    ('United States', 'United States of America', 'US', '.us', '', 'The Star-Spangled Banner', 'Washington, D.C.', 'English', 332403650, 'US', 'USA', '+1', 'UTC-5', 155, 155, 6, 1, 1, 4),
    ('Uruguay', 'Oriental Republic of Uruguay', 'UY', '.uy', '', 'Himno Nacional de Uruguay', 'Montevideo', 'Spanish', 3537380, 'UY', 'URY', '+598', 'UTC-3', 134, 134, 155, 1, 1, 1),
    ('Uzbekistan', 'Republic of Uzbekistan', 'UZ', '.uz', '', "O'zbekiston milliy gimni", 'Tashkent', 'Uzbek', 35205283, 'UZ', 'UZB', '+998', 'UTC+5', 136, 136, 156, 2, 2, 5),
    ('Venezuela', 'Bolivarian Republic of Venezuela', 'VE', '.ve', '', 'Gloria al Bravo Pueblo', 'Caracas', 'Spanish', 33199905, 'VE', 'VEN', '+58', 'UTC-4', 137, 137, 158, 1, 1, 1),
    ('Vietnam', 'Socialist Republic of Vietnam', 'VN', '.vn', '', 'Tiến Quân Ca', 'Hanoi', 'Vietnamese', 99533972, 'VN', 'VNM', '+84', 'UTC+7', 138, 138, 159, 2, 2, 7),
    ('Vanuatu', 'Republic of Vanuatu', 'VU', '.vu', '', 'We Are Proud to Stand Beside You', 'Port Vila', 'Bislama', 322957, 'VU', 'VUT', '+688', 'UTC+11', 139, 139, 157, 1, 5, 23),
    ('Samoa', 'Independent State of Samoa', 'WS', '.ws', 'Fa''avae le Atua Samoa', 'The Banner of Freedom', 'Apia', 'Samoan', 201498, 'WS', 'WSM', '+685', 'UTC+13', 143, 143, 128, 1, 5, 23),
    ('Economic and Monetary Community of Central Africa', 'Economic and Monetary Community of Central Africa', 'CEMAC', '-', '-', '-', '-', '-', 0, '-', '-', '-', '-', NULL, NULL, 27, NULL, NULL, NULL),
    ('Organization of Eastern Caribbean States', 'Organization of Eastern Caribbean States', 'OECS', '-', '-', '-', '-', '-', 0, '-', '-', '-', '-', NULL, NULL, 116, NULL, NULL, NULL),
    ('International Monetary Fund', 'International Monetary Fund', 'IMF', '.imf', '-', '-', '-', '-', 0, '-', '-', '-', '-', NULL, NULL, 82, NULL, NULL, NULL),
    ('West African CFA franc', 'West African CFA franc', 'CFA', '-', '-', '-', '-', '-', 0, '-', '-', '-', '-', NULL, NULL, 49, NULL, NULL, NULL),
    ("Collectivités d'Outre-Mer", "Collectivités d'Outre-Mer", 'COM', '-', '-', '-', '-', '-', 0, '-', '-', '-', '-', NULL, NULL, 51, NULL, NULL, NULL),
    ('Yemen', 'Republic of Yemen', 'YE', '.ye', '-', '-', 'Sanaa', 'Arabic', 31615683, 'YE', 'YEM', '+967', '-', 149, 149, 160, 1, 1, 10),
    ('South Africa', 'Republic of South Africa', 'ZA', '.za', '-', "Nkosi Sikelel' iAfrika", 'Pretoria (administrative), Bloemfontein (judicial), Cape Town (legislative)', 'Afrikaans',  59475057, 'ZA', 'ZAF', '+27', 'UTC+2', 140, 140, 62, 3, 3, 14),
    ('Zambia', 'Republic of Zambia', 'ZM', '.zm', '-', 'Stand and Sing of Zambia, Proud and Free', 'Lusaka', 'English', 18984400, 'ZM', 'ZMB', '+260', 'UTC+2', 147, 147, 160, 3, 3, 14),
    ('Zimbabwe', 'Republic of Zimbabwe', 'ZW', '.zw', '-', 'Simudza WeZimbabwe', 'Harare', 'English', 15042978, 'ZW', 'ZWE', '+263', 'UTC+2', 148, 148, 161, 3, 3, 14);