# fly.toml app configuration file generated for countries-sundries-api-late-morning-5934-broken-forest-3067 on 2024-03-14T00:58:02-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'countries-sundries-api-late-morning-5934-broken-forest-3067'
primary_region = 'sea'

[build]

[deploy]
  release_command = 'bun run migrate'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
